# Generated by Django 4.0 on 2022-01-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Ingredient name')),
                ('article_number', models.CharField(max_length=24, verbose_name='Article number')),
                ('base_measurement_unit', models.CharField(choices=[('g', 'grams'), ('Kg', 'kilograms'), ('cL', 'centiliter'), ('L', 'liter')], max_length=2, verbose_name='Measurement Unit')),
                ('base_amount', models.FloatField(default=0, verbose_name='Buying Amount')),
                ('cost_per_base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost per buying amount')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ('name', 'article_number'),
            },
        ),
    ]
