# Generated by Django 4.0 on 2021-12-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('base_measurement_unit', models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('cl', 'centiliter'), ('l', 'liter')], max_length=2)),
                ('base_amount', models.FloatField(default=0)),
                ('cost_per_base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
