# Generated by Django 4.0 on 2022-01-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='article_number',
            field=models.CharField(default='', max_length=24, verbose_name='Article number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_amount',
            field=models.FloatField(default=0, verbose_name='Buying Amount'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_measurement_unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('cl', 'centiliter'), ('l', 'liter')], max_length=2, verbose_name='Measurement Unit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost_per_base_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost per buying amount'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Ingredient name'),
        ),
    ]
