# Generated by Django 4.0 on 2022-01-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeingredient_recipe_ingredient'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='recipe_ingredient',
        ),
    ]
